// Datasource of rows , columns file for the [Contacts] file :

// Define {columns} array of objects :
export const columns = [
  { field: "id", headerName: "ID", width: 100 },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    align: "left",
    width: 100,
  },
  { field: "phone", headerName: "Phone Number", flex: 1 },
  { field: "email", headerName: "Email", flex: 1 },
  { field: "address", headerName: "Address", flex: 1 },
  { field: "city", headerName: "city", flex: 1 },
  { field: "zipcode", headerName: "Zip Code", flex: 1 },
];

// Define {rows} array of objects :
export const rows = [
  {
    id: 1,
    name: "Shadi Sayed",
    age: "37",
    phone: "20589543",
    email: "shadisyaed@gmail.com",
    address: "Cairo",
    city: "Cairo",
    zipcode: "11858",
  },
  {
    id: 2,
    name: "Ali Hassan",
    age: "30",
    phone: "56748906",
    email: "alihassan@gmail.com",
    address: "Alexandria",
    city: "Alexandria",
    zipcode: "22239",
  },
  {
    id: 3,
    name: "Mohammed Ahmed",
    age: "40",
    phone: "68656",
    email: "mohammedahmed@gmail.com",
    address: "Domiat",
    city: "Domiat",
    zipcode: "11115",
  },
  {
    id: 4,
    name: "Mohammed Mostafa",
    age: "41",
    phone: "555796",
    email: "mohammedmostafa@gmail.com",
    address: "Begera",
    city: "Begera",
    zipcode: "3298",
  },
  {
    id: 5,
    name: "Amr Youssef",
    age: "43",
    phone: "0551698",
    email: "amryoussef@gmail.com",
    address: "Banha",
    city: "Banha",
    zipcode: "996",
  },
  {
    id: 6,
    name: "Huda Sultan",
    age: "35",
    phone: "5774",
    email: "hudasultan@gmail.com",
    address: "Sharm El shiekh",
    city: "Sharm El shiekh",
    zipcode: "545447",
  },
  {
    id: 7,
    name: "Abel Rahman",
    age: "28",
    phone: "010567779364",
    email: "abelrahman@gmail.com",
    address: "Giza",
    city: "Giza",
    zipcode: "63338",
  },
];
