// Seperted file of the [array of All projects]    :  

// Define array of All projects , to use it with mapping inside th displayed cards :
export const projects = [
    {
      id: "1",
      projectTitle: "React & MUI Project",
      projectSubTitle: "Fullstack Ecommerce Project created by using + Vite React framework + React MUI + Strapi & Cloudinary CMS + Render Backend service +  Hosted by Firebase Google Hosting service  ",
      imgPath: "/1.jpg",
      category: ["React"],
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/My Portfolio Projects/ReactJS  MUI Vite Strapi Fullstack/Fullstack/E-commerce Work",
      link: "https://ecommerce-a0154.web.app",
    },
    {
      id: "2",
      projectTitle: "React & CSS Project",
      projectSubTitle: "My Portfolio of this web App Project created by using + Vite React framework + CSS + Hosted by Firebase Google Hosting service ",
      imgPath: "/2.jpg",
      category: ["React"],
      link: "https://react-portfolio-caf81.web.app",
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/My Portfolio Projects/ReactJS Vite CSS/Frontend/portfolio",
    },
    {
      id: "3",
      projectTitle: "React Fullstack App & API Project",
      projectSubTitle: "Fullstack Movies Listing database Project created by using React framework + CSS + Backend by themoviedb.org Real Restful Api +  Hosted by Firebase Google Hosting service ",
      imgPath: "/3.jpg",
      category: ["React"],
      link: "https://movies-db-4e5fc.web.app",
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/My Portfolio Projects/ReactJS and Redux/Fullstack/Movies Database",
    },
    {
      id: "4",
      projectTitle: "React Redux Fullstack App & API Project",
      projectSubTitle: "Fullstack Movies Listing database Project created by using React framework + Redux System + CSS + Backend by themoviedb.org Real Restful Api +  Hosted by Firebase Google Hosting service  ",
      imgPath: "/4.jpg",
      category: ["React"],
      link: "https://movies-db-redux.web.app/",
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/My Portfolio Projects/ReactJS and Redux/Fullstack/Movies Database Redux",
    },
    {
      id: "5",
      projectTitle: "React Simple Project",
      projectSubTitle: "Simple React App of  Meals Menu Project created by using React framework + CSS + Hosted by Firebase Google Hosting service  ",
      imgPath: "/5.jpg",
      category: [ "React" ],
      link: "https://meals-list-cb255.web.app/",
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/My Portfolio Projects/ReactJS and Redux/Frontend/meals-list",
    },
    {
      id: "6",
      projectTitle: "React Simple Project",
      projectSubTitle: "Simple React App of Dates Reminder Project created by using React framework + CSS + Hosted by Firebase Google Hosting service  ",
      imgPath: "/6.jpg",
      category: [ "React" ],
      link: "https://dates-reminder-e93da.web.app/",
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/My Portfolio Projects/ReactJS and Redux/Frontend/dates-reminders",
    },
    {
      id: "7",
      projectTitle: "HTML & CSS Project",
      projectSubTitle: "Project created by using HTML CSS ",
      imgPath: "/7.jpg",
      category: ["HTML & CSS"],
      link: "",
      githubLink: "",
    },
    {
      id: "8",
      projectTitle: "JavaScript Project",
      projectSubTitle: "To-Do List application created by using HTML + CSS + JavaScript",
      imgPath: "/8.jpg",
      category: ["JavaScript"],
      link: "../../../projects/todo list project Adv/index.html",
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/My Portfolio Projects/HTML CSS JS/Frontend/To-Do List",
    },
    {
      id: "9",
      projectTitle: "JavaScript Project",
      projectSubTitle: "Javascript Game application project created by using JavaScript ",
      imgPath: "/9.jpg",
      category: ["JavaScript"],
      link: "../../../projects/js game Hit Mole/index.html",
      githubLink: "",
    },
    {
      id: "10",
      projectTitle: "JavaScript Project",
      projectSubTitle: "JavaScript Testing Typing Speed application project created by using JavaScript ",
      imgPath: "/b.png",
      category: ["JavaScript"],
      link: "../../../projects/js simple typing game/index.html",
      githubLink: "",
    },
    {
      id: "11",
      projectTitle: "JavaScript Project",
      projectSubTitle: "JavaScript Cubes game application project created by using JavaScript ",
      imgPath: "/q.png",
      category: ["JavaScript"],
      link: "../../../projects/js cubes game/index.html",
      githubLink: "",
    },
    {
      id: "12",
      projectTitle: "Javascript Project",
      projectSubTitle: "Javascript X O game application Project created by using Javascript ",
      imgPath: "/1.jpg",
      category: ["JavaScript"],
      link: "../../../projects/js X O game/index.html",
      githubLink: "",
    },
    {
      id: "13",
      projectTitle: "Javascript Project",
      projectSubTitle: "Javascript image editor application Project created by using Javascript",
      imgPath: "/3.jpg",
      category: ["JavaScript"],
      link: "../../../projects/js simple image editor/index.html",
      githubLink: "",
    },
    {
      id: "14",
      projectTitle: "Javascript Project",
      projectSubTitle: "Javascript simple calculator application Project created by using Javascript",
      imgPath: "/4.jpg",
      category: ["JavaScript"],
      link: "../../../projects/js simple calculator/index.html",
      githubLink: "",
    },
  ];
  
  