// Seperted file of the [array of All projects]    :  

// Define array of All projects , to use it with mapping inside th displayed cards :
export const projects = [
    {
      id: "1",
      projectTitle: "react & Bootstrap Project",
      projectSubTitle: "Project created by using React framework ",
      imgPath: "/1.jpg",
      category: ["React", "Bootstrap"],
      link: "",
    },
    {
      id: "2",
      projectTitle: "React & Bootstrap Project",
      projectSubTitle: "Project created by using React framework ",
      imgPath: "/2.jpg",
      category: ["React", "Bootstrap"],
      link: "",
    },
    {
      id: "3",
      projectTitle: "React & Bootstrap Project",
      projectSubTitle: "Project created by using React framework ",
      imgPath: "/3.jpg",
      category: ["React", "Bootstrap"],
      link: "",
    },
    {
      id: "4",
      projectTitle: "React & MUI Project",
      projectSubTitle: "Project created by using React framework ",
      imgPath: "/4.jpg",
      category: ["React", "MUI"],
      link: "",
    },
    {
      id: "5",
      projectTitle: "HTML & CSS Project",
      projectSubTitle: "Project created by using HTML CSS ",
      imgPath: "/5.jpg",
      category: ["HTML & CSS"],
      link: "",
    },
    {
      id: "6",
      projectTitle: "HTML & CSS Project",
      projectSubTitle: "Project created by using HTML CSS ",
      imgPath: "/6.jpg",
      category: ["HTML & CSS"],
      link: "",
    },
    {
      id: "7",
      projectTitle: "HTML & CSS Project",
      projectSubTitle: "Project created by using HTML CSS ",
      imgPath: "/7.jpg",
      category: ["HTML & CSS"],
      link: "",
    },
    {
      id: "8",
      projectTitle: "JavaScript Project",
      projectSubTitle: "Project created by using JavaScript ",
      imgPath: "/8.jpg",
      category: ["JavaScript"],
      link: "",
    },
    {
      id: "9",
      projectTitle: "JavaScript Project",
      projectSubTitle: "Project created by using JavaScript ",
      imgPath: "/9.jpg",
      category: ["JavaScript"],
      link: "",
    },
    {
      id: "10",
      projectTitle: "JavaScript Project",
      projectSubTitle: "Project created by using JavaScript ",
      imgPath: "/b.png",
      category: ["JavaScript"],
      link: "",
    },
    {
      id: "11",
      projectTitle: "NextJS Project",
      projectSubTitle: "Project created by using NextJS framework ",
      imgPath: "/d.webp",
      category: ["NextJS"],
      link: "",
    },
    {
      id: "12",
      projectTitle: "NextJS Project",
      projectSubTitle: "Project created by using NextJS framework ",
      imgPath: "/q.png",
      category: ["NextJS"],
      link: "",
    },
    {
      id: "13",
      projectTitle: "NextJS Project",
      projectSubTitle: "Project created by using NextJS framework ",
      imgPath: "/1.jpg",
      category: ["NextJS"],
      link: "",
    },
  ];
  
  