// Seperted file of the [array of All projects]    :  

// Define array of All projects , to use it with mapping inside th displayed cards :
export const projects = [
    {
      id: "1",
      projectTitle: "React & MUI Project",
      projectSubTitle: "Fullstack Ecommerce Project created by using + Vite React framework + React MUI + Strapi & Cloudinary CMS + Render Backend service +  Hosted by Firebase Google Hosting service  ",
      imgPath: "/1.jpg",
      category: ["React"],
      link: "https://ecommerce-a0154.web.app",
    },
    {
      id: "2",
      projectTitle: "React & CSS Project",
      projectSubTitle: "My Portfolio of this web App Project created by using + Vite React framework + CSS + Hosted by Firebase Google Hosting service ",
      imgPath: "/2.jpg",
      category: ["React"],
      link: "https://react-portfolio-caf81.web.app",
    },
    {
      id: "3",
      projectTitle: "React Fullstack App & API Project",
      projectSubTitle: "Fullstack Movies Listing database Project created by using React framework + CSS + Backend by themoviedb.org Real Restful Api +  Hosted by Firebase Google Hosting service  ",
      imgPath: "/3.jpg",
      category: ["React"],
      link: "https://movies-db-4e5fc.web.app",
    },
    {
      id: "4",
      projectTitle: "React Redux Fullstack App & API Project",
      projectSubTitle: "Fullstack Movies Listing database Project created by using React framework + Redux System + CSS + Backend by themoviedb.org Real Restful Api +  Hosted by Firebase Google Hosting service  ",
      imgPath: "/4.jpg",
      category: ["React"],
      link: "https://movies-db-redux.web.app/",
    },
    {
      id: "5",
      projectTitle: "React Simple Project",
      projectSubTitle: "Simple React App of  Meals Menu Project created by using React framework + CSS + Hosted by Firebase Google Hosting service  ",
      imgPath: "/5.jpg",
      category: [ "React" ],
      link: "https://meals-list-cb255.web.app/",
    },
    {
      id: "6",
      projectTitle: "React Simple Project",
      projectSubTitle: "Simple React App of Dates Reminder Project created by using React framework + CSS + Hosted by Firebase Google Hosting service  ",
      imgPath: "/6.jpg",
      category: [ "React" ],
      link: "https://dates-reminder-e93da.web.app/",
    },
    {
      id: "7",
      projectTitle: "HTML & CSS Project",
      projectSubTitle: "Project created by using HTML CSS ",
      imgPath: "/7.jpg",
      category: ["HTML & CSS"],
      link: "",
    },
    {
      id: "8",
      projectTitle: "JavaScript Project",
      projectSubTitle: "Project created by using JavaScript ",
      imgPath: "/8.jpg",
      category: ["JavaScript"],
      link: "",
    },
    {
      id: "9",
      projectTitle: "JavaScript Project",
      projectSubTitle: "Project created by using JavaScript ",
      imgPath: "/9.jpg",
      category: ["JavaScript"],
      link: "",
    },
    {
      id: "10",
      projectTitle: "JavaScript Project",
      projectSubTitle: "Project created by using JavaScript ",
      imgPath: "/b.png",
      category: ["JavaScript"],
      link: "",
    },
    {
      id: "11",
      projectTitle: "NextJS Project",
      projectSubTitle: "Project created by using NextJS framework ",
      imgPath: "/d.webp",
      category: ["NextJS"],
      link: "",
    },
    {
      id: "12",
      projectTitle: "NextJS Project",
      projectSubTitle: "Project created by using NextJS framework ",
      imgPath: "/q.png",
      category: ["NextJS"],
      link: "",
    },
    {
      id: "13",
      projectTitle: "NextJS Project",
      projectSubTitle: "Project created by using NextJS framework ",
      imgPath: "/1.jpg",
      category: ["NextJS"],
      link: "",
    },
  ];
  
  