// Datasource of rows , columns file for the [Invoices] file :

// Define {columns} array of objects :
export const columns = [
  { field: "id", headerName: "ID", width: 100 },
  {
    field: "name",
    headerName: "Name",
    cellClassName: "name-column--cell",
},
{ field: "email", headerName: "Email", flex: 1 },
{
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "left",
    flex: 1,
    align: "left",
  },
  { field: "phone", headerName: "Phone Number", flex: 1 },
  { field: "address", headerName: "Address", flex: 1 },
  { field: "city", headerName: "city", flex: 1 },
  { field: "zipcode", headerName: "Zip Code" },
  { field: "registrarId", headerName: "Registrar ID" },
];

// Define {rows} array of objects :
export const rows = [
  {
    id: 1,
    name: "Shadi Sayed",
    email: "shadisyaed@gmail.com",
    age: "37",
    phone: "20589543",
    address: "Cairo",
    city: "Cairo",
    zipcode: "11858",
    registrarId: 533215,
  },
  {
    id: 2,
    name: "Ali Hassan",
    email: "alihassan@gmail.com",
    age: "30",
    phone: "56748906",
    address: "Alexandria",
    city: "Alexandria",
    zipcode: "22239",
    registrarId: 533215,
  },
  {
    id: 3,
    name: "Mohammed Ahmed",
    email: "mohammedahmed@gmail.com",
    age: "40",
    phone: "68656",
    address: "Domiat",
    city: "Domiat",
    zipcode: "11115",
    registrarId: 533215,
  },
  {
    id: 4,
    name: "Mohammed Mostafa",
    email: "mohammedmostafa@gmail.com",
    age: "41",
    phone: "555796",
    address: "Begera",
    city: "Begera",
    zipcode: "3298",
    registrarId: 533215,
  },
  {
    id: 5,
    name: "Amr Youssef",
    age: "43",
    phone: "0551698",
    email: "amryoussef@gmail.com",
    address: "Banha",
    city: "Banha",
    zipcode: "996",
    registrarId: 533215,
  },
  {
    id: 6,
    name: "Huda Sultan",
    age: "35",
    phone: "5774",
    email: "hudasultan@gmail.com",
    address: "Sharm El shiekh",
    city: "Sharm El shiekh",
    zipcode: "545447",
    registrarId: 533215,
  },
  {
    id: 7,
    name: "Abel Rahman",
    age: "28",
    phone: "010567779364",
    email: "abelrahman@gmail.com",
    address: "Giza",
    city: "Giza",
    zipcode: "63338",
    registrarId: 533215,
  },
  {
    id: 8,
    name: "Hytham Gamal",
    age: "35",
    phone: "0105677793568",
    email: "hythamgamal@gmail.com",
    address: "Cairo",
    city: "Cairo",
    zipcode: "6333688",
    registrarId: 6844515,
  },
  {
    id: 9,
    name: "Farouq Ali",
    age: "25",
    phone: "01056777684634",
    email: "farouqali@gmail.com",
    address: "Giza",
    city: "Giza",
    zipcode: "65558",
    registrarId: 697497,
  },
  {
    id: 10,
    name: "Ahmed Bassuni",
    age: "38",
    phone: "0115553779364",
    email: "ahmedbassuni@gmail.com",
    address: "Alexandria",
    city: "Alexandria",
    zipcode: "654973",
    registrarId: 565493,
  },
];
