
// Seperted file of the [array of All References courses lessons ]    :  

  // Define array of All References courses , to use it with mapping inside th displayed cards :
  export const refs = [
    {
      id: "1",
      courseTitle: "HTML5",
      courseSubTitle: "My HTML5 Course ",
      imgPath: "/refs images/html 5.png",
      category: ["HTML5"],
      link: "https://shandowpro.github.io/refs/1%20HTML5%20Course/course%20map/HTML5%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/1 HTML5 Course",
    },
    {
      id: "2",
      courseTitle: "CSS 2",
      courseSubTitle: "My CSS 2 Course ",
      imgPath: "/refs images/CSS.png",
      category: ["CSS 2"],
      link: "https://shandowpro.github.io/refs/2%20CSS%202%20Course/course%20map/CSS2%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/2 CSS 2 Course",
    },
    {
      id: "3",
      courseTitle: "CSS 3",
      courseSubTitle: "My CSS 3 Course ",
      imgPath: "/refs images/CSS 3.png",
      category: ["CSS 3"],
      link: "https://shandowpro.github.io/refs/3%20CSS3%20Course/course%20map/CSS3%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/3 CSS3 Course",
    },
    {
      id: "4",
      courseTitle: "JavaScript Basics",
      courseSubTitle: "My JavaScript Basics Course ",
      imgPath: "/refs images/JS.png",
      category: ["JavaScript Basics"],
      link: "https://shandowpro.github.io/refs/4%20JavaScript%20Course/course%20map/Javascript%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/4 JavaScript Course", 
    },     
    {
      id: "5",
      courseTitle: "JavaScript ES6+",
      courseSubTitle: "My JS Ecma Script 6+ Course ",
      imgPath: "/refs images/JS ES6.png",
      category: ["JavaScript ES6+"],
      link: "https://shandowpro.github.io/refs/21%20Ecma%20Script%206/course%20map/ES6+%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/21 Ecma Script 6", 
    },
    {
      id: "6",
      courseTitle: "MySQL",
      courseSubTitle: "MySQL Course ",
      imgPath: "/refs images/mysql.jpg",
      category: ["MySQL"],
      link: "https://shandowpro.github.io/refs/15%20MySQL%20Course/course%20map/MySQL%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/15 MySQL Course", 
    },  
    {
      id: "7",
      courseTitle: "Typescript",
      courseSubTitle: "My TypeScript Course ",
      imgPath: "/refs images/TS.png",
      category: ["Typescript"],
      link: "https://shandowpro.github.io/refs/20%20TypeScript/course%20map/TypeScript%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/20 TypeScript",
    },
    {
      id: "8",
      courseTitle: "ReactJs Redux",
      courseSubTitle: "My ReactJs Redux Course ",
      imgPath: "/refs images/React.png",
      category: ["ReactJs"],
      link: "https://shandowpro.github.io/refs/24%20ReactJS%20Redux%20Basics/course%20map/React%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/24 ReactJS Redux Basics",
    },
    {
      id: "9",
      courseTitle: "BOM",
      courseSubTitle: "My BOM Course ",
      imgPath: "/refs images/JS BOM.png",
      category: ["BOM"],
      link: "https://shandowpro.github.io/refs/6%20JS%20BOM%20Course/course%20map/BOM%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/6 JS BOM Course",
    },
    {
      id: "10",
      courseTitle: "DOM",
      courseSubTitle: "My DOM Course ",
      imgPath: "/refs images/JS DOM.png",
      category: ["DOM"],
      link: "https://shandowpro.github.io/refs/7%20JS%20DOM%20Course/course%20map/DOM%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/7 JS DOM Course" , 
    },
    {
      id: "11",
      courseTitle: "JQuery",
      courseSubTitle: "My JQuery Course ",
      imgPath: "/refs images/JQuery.png",
      category: ["JQuery"],
      link: "https://shandowpro.github.io/refs/16%20JQuery%20Course/course%20map/jQuery%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/16 JQuery Course",  
    },
    {
      id: "12",
      courseTitle: "JSOOP",
      courseSubTitle: "My JSOOP Course ",
      imgPath: "/refs images/JS OOP.jpg",
      category: ["JSOOP"],
      link: "https://shandowpro.github.io/refs/5%20JavaScript%20OOP%20Course/course%20map/JavaScript%20OOP%20Course.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/5 JavaScript OOP Course" ,
    },
    {
      id: "13",
      courseTitle: "PHP",
      courseSubTitle: "My PHP Course ",
      imgPath: "/refs images/php.png",
      category: ["PHP"],
      link: "https://shandowpro.github.io/refs/8%20PHP%20Course/course%20map/PHP%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/8 PHP Course" , 
    },
    {
      id: "14",
      courseTitle: "PHPOOP",
      courseSubTitle: "My PHPOOP Course ",
      imgPath: "/refs images/PHP oop.jpg",
      category: ["PHPOOP"],
      link: "https://shandowpro.github.io/refs/9%20PHP%20OOP%20Course/course%20map/PHP%20OOP%20Course.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/9 PHP OOP Course" , 
    },
    {
      id: "15",
      courseTitle: "CMD",
      courseSubTitle: "My Command line Course ",
      imgPath: "/refs images/cmd 0.png",
      category: ["CMD"],
      link: "https://shandowpro.github.io/refs/14%20Command%20Line%20Course/course%20map/Command%20Line%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/14 Command Line Course" , 
    },
    {
      id: "16",
      courseTitle: "Github",
      courseSubTitle: "My Github Course ",
      imgPath: "/refs images/github.jpg",
      category: ["Github"],
      link: "https://shandowpro.github.io/refs/13%20Git%20and%20Git%20Hub%20Course/course%20map/Github%20Course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/13 Git and Git Hub Course", 
    },
    {
      id: "17",
      courseTitle: "Bootstrap",
      courseSubTitle: "My Bootstrap Course ",
      imgPath: "/refs images/Bootstrap.jpg",
      category: ["Bootstrap"],
      link: "https://shandowpro.github.io/refs/12%20Bootstrap3%20Design1%20Twitter%20Course/course%20map/Bootstrap%20course%20map.html" , 
      githubLink: "https://github.com/shandowpro/mywebpages/tree/master/12 Bootstrap3 Design1 Twitter Course" , 
    },

  ];
  
  