import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <ul
            style={{ border: "solid red 3px", margin: "10px", padding: "5px" }}
          >
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/contact"> Go to Contact page </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/products"> Go to Products page 'including a dynamic router - productId' </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/portfolio"> Go to portfolio page </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson3">
                {" "}
                Go to lesson3 : '3 Initializing ReactJS App by VScode'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson4">
                {" "}
                Go to lesson4 : '4 Main ReatJS Syntax with page.tsx file'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson5">
                {" "}
                Go to lesson5 : '5 using props or Params and type object with
                children components'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson6">
                {" "}
                Go to lesson6 : '6 Arrange Syntax of page.tsx with other
                children components'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson7">
                {" "}
                Go to lesson7 : '7 conditaional Rendering with Including
                Compoenents'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson8">
                {" "}
                Go to lesson8 : '8 Styling in ReactJS'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson9">
                {" "}
                Go to lesson9 : '9 Routers and Routing in ReactJS'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson10">
                {" "}
                Go to lesson10 : '10 Hocks and useState in ReactJS'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson11">
                {" "}
                Go to lesson11 : '11 Hocks and useEffect in ReactJS'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson12">
                {" "}
                Go to lesson12 : '12 Hocks and useRef in ReactJS'{" "}
              </Link>{" "}
            </li>
            <li style={{ listStyle: "none" }}>
              {" "}
              <Link href="/lesson13">
                {" "}
                Go to lesson13 : '13 Hocks and useMemo in ReactJS'{" "}
              </Link>{" "}
            </li>
          </ul>
        </div>

        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>


        <div>
          <h2> Our Products  </h2> 
          <nav>
           {/* Creating dynmaic links of following items : */}
            <ul> 
                <li> 
                   <Link href={'/products/product1'} > Product1 </Link>
                </li>

                <li>
                   <Link href={'/products/product2'} > Product2 </Link>
                </li>
                
                <li>
                   <Link href={'/products/product3'} > Product3 </Link>
                </li>
              </ul>  
          </nav> 

        </div>
      </main>
    </>
  );
}
